spring:
  config:
    activate:
      on-profile: local
  datasource:
    username:
    password:
    driver-class-name:
    url:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
  server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/app/config/backend/application.yml